### ISSUE TITLE
Multiple accumulative jobs executions

### ISSUE THREAD

**Issue by kroshilin** [Cron/Symfony-Bundle#137]
`Cron\Executor\Executor` has `array sets` property, which seems never clean up. I suppose, by original design of Cron package, it should be always new instance of Executor, so `sets` always empty on cron run.
When running in blocking mode (`--blocking`), Executor is taken from `$this->getContainer()->get('cron.executor')`, and this service is shared, so we get same instance on each cron run. `Sets` are in memory and stored already executed jobs, so on each run all previously done jobs will be executed again.  
As tmp solution add to your services.yaml:
```
  cron.executor:
        class: Cron\Executor\Executor
        shared: false
        public: true

```
